//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHILD_STANDARD_BMI
    {
        public decimal ID { get; set; }
        public Nullable<decimal> YF { get; set; }
        public string SEX { get; set; }
        public string BMI_3TH { get; set; }
        public string BMI_5TH { get; set; }
        public string BMI_10TH { get; set; }
        public string BMI_15TH { get; set; }
        public string BMI_25TH { get; set; }
        public string BMI_50TH { get; set; }
        public string BMI_75TH { get; set; }
        public string BMI_85TH { get; set; }
        public string BMI_90TH { get; set; }
        public string BMI_95TH { get; set; }
        public string BMI_97TH { get; set; }
    }
}
