//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHILD_YINGYANGGEAN
    {
        public decimal ID { get; set; }
        public Nullable<decimal> CHILDID { get; set; }
        public string JIWANGSHI { get; set; }
        public string ENDTIME { get; set; }
        public string MANAGETIME { get; set; }
        public string ZHUANGUI { get; set; }
        public string CHUSHENGSHI { get; set; }
        public string WEIYANGSHI { get; set; }
        public string FOODCHANGE { get; set; }
        public string YUNZHOU { get; set; }
        public string YUNTIAN { get; set; }
        public string HB { get; set; }
        public string TIEJI { get; set; }
        public string YAOWU { get; set; }
        public string JILIANG { get; set; }
        public string LIAOCHENG { get; set; }
        public string MURU { get; set; }
        public string FOODAGE { get; set; }
        public string BURUQI { get; set; }
        public string CHILDVITD { get; set; }
        public string STARTVITDMONTH { get; set; }
        public string STARTVITDDAY { get; set; }
        public string VITDNAME { get; set; }
        public string VITDLIANG { get; set; }
        public string TIZHENG { get; set; }
        public string XUEGAI { get; set; }
        public string XUELIN { get; set; }
        public string XUEAKP { get; set; }
        public string XUEOH { get; set; }
        public string XJIANCHA { get; set; }
        public string RECORDTIME { get; set; }
        public string RECORDNAME { get; set; }
    }
}
