//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHILD_STANDARD_W_H
    {
        public decimal ID { get; set; }
        public string SEX { get; set; }
        public Nullable<decimal> HIGHT { get; set; }
        public string WD_3TH { get; set; }
        public string WD_5TH { get; set; }
        public string WD_10TH { get; set; }
        public string WD_15TH { get; set; }
        public string WD_25TH { get; set; }
        public string WD_50TH { get; set; }
        public string WD_75TH { get; set; }
        public string WD_85TH { get; set; }
        public string WD_90TH { get; set; }
        public string WD_95TH { get; set; }
        public string WD_97TH { get; set; }
    }
}
