//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHILD_PINXUEGEAN_RECORD
    {
        public decimal ID { get; set; }
        public Nullable<decimal> CHILDID { get; set; }
        public Nullable<decimal> CHECKID { get; set; }
        public string HB { get; set; }
        public string PROBLEM { get; set; }
        public string ZHILIAO { get; set; }
        public string YAOWU { get; set; }
        public string JILIANG { get; set; }
        public string ZHIDAO { get; set; }
    }
}
