//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHILD_STANDARD
    {
        public decimal ID { get; set; }
        public Nullable<decimal> YF { get; set; }
        public string SEX { get; set; }
        public string WD_3TH { get; set; }
        public string WD_5TH { get; set; }
        public string WD_10TH { get; set; }
        public string WD_25TH { get; set; }
        public string WD_50TH { get; set; }
        public string WD_75TH { get; set; }
        public string WD_90TH { get; set; }
        public string WD_95TH { get; set; }
        public string WD_97TH { get; set; }
        public string HT_3TH { get; set; }
        public string HT_5TH { get; set; }
        public string HT_10TH { get; set; }
        public string HT_25TH { get; set; }
        public string HT_50TH { get; set; }
        public string HT_75TH { get; set; }
        public string HT_90TH { get; set; }
        public string HT_95TH { get; set; }
        public string HT_97TH { get; set; }
        public string TW_3TH { get; set; }
        public string TW_5TH { get; set; }
        public string TW_10TH { get; set; }
        public string TW_25TH { get; set; }
        public string TW_50TH { get; set; }
        public string TW_75TH { get; set; }
        public string TW_90TH { get; set; }
        public string TW_95TH { get; set; }
        public string TW_97TH { get; set; }
    }
}
