//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CP_ADOS1_TAB
    {
        public decimal ID { get; set; }
        public decimal CHILD_ID { get; set; }
        public string GT_CXTR { get; set; }
        public string GT_KB { get; set; }
        public string GT_SYTRST { get; set; }
        public string GT_ZWDZ { get; set; }
        public string GT_ZSDZ { get; set; }
        public string GT_SUM { get; set; }
        public string HD_BXC { get; set; }
        public string HD_CXTR { get; set; }
        public string HD_HDZGXLQ { get; set; }
        public string HD_ZS { get; set; }
        public string HD_ZFDZD { get; set; }
        public string HD_DXHXT { get; set; }
        public string HD_ZDBD { get; set; }
        public string HD_SUM { get; set; }
        public string GT_HD_SUM { get; set; }
        public string YX_SYWP { get; set; }
        public string YX_XX { get; set; }
        public string YX_SUM { get; set; }
        public string KBXW_DYXSC { get; set; }
        public string KBXW_SHSZ { get; set; }
        public string KBXW_BTXC { get; set; }
        public string KBXW_SUM { get; set; }
        public string JL { get; set; }
        public string PGZQM { get; set; }
        public string PGRQ { get; set; }
        public string OPERATE_NAME { get; set; }
        public string OPERATE_CODE { get; set; }
        public string OPERATE_TIME { get; set; }
        public string UPDATE_NAME { get; set; }
        public string UPDATE_CODE { get; set; }
        public string UPDATE_TIME { get; set; }
        public string SZYS { get; set; }
        public string HOSPITAL { get; set; }
        public string BZ { get; set; }
        public string BZ_VISIBLE { get; set; }
    }
}
