//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CP_ASD2_TAB
    {
        public decimal ID { get; set; }
        public decimal CHILD_ID { get; set; }
        public string SRS_ZJ { get; set; }
        public string SRS_RZ { get; set; }
        public string SRS_JLIU { get; set; }
        public string SRS_DJ { get; set; }
        public string SRS_XWFS { get; set; }
        public string SRS_ZLB { get; set; }
        public string SRS_JL { get; set; }
        public string ABC_DF { get; set; }
        public string ABC_JL { get; set; }
        public string CSZQM { get; set; }
        public string CSRQ { get; set; }
        public string OPERATE_NAME { get; set; }
        public string OPERATE_CODE { get; set; }
        public string OPERATE_TIME { get; set; }
        public string UPDATE_NAME { get; set; }
        public string UPDATE_CODE { get; set; }
        public string UPDATE_TIME { get; set; }
        public string SZYS { get; set; }
        public string HOSPITAL { get; set; }
        public string BZ { get; set; }
        public string BZ_VISIBLE { get; set; }
    }
}
