//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CP_ADHD_TAB
    {
        public decimal ID { get; set; }
        public decimal CHILD_ID { get; set; }
        public string ADHD1_BSTGZ { get; set; }
        public string ADHD1_PF { get; set; }
        public string ADHD1_JL { get; set; }
        public string ADHD2_BSTGZ { get; set; }
        public string ADHD2_ZYQX { get; set; }
        public string ADHD2_ZYQX_SUM { get; set; }
        public string ADHD2_DDCD { get; set; }
        public string ADHD2_DDCD_SUM { get; set; }
        public string ADHD2_GNSH { get; set; }
        public string ADHD2_GNSH_SUM { get; set; }
        public string ADHD2_JL { get; set; }
        public string ADHD3_BSTGZ { get; set; }
        public string ADHD3_DLWK { get; set; }
        public string ADHD3_DLWK_SUM { get; set; }
        public string ADHD3_PXZA { get; set; }
        public string ADHD3_PXZA_SUM { get; set; }
        public string ADHD3_JLYY { get; set; }
        public string ADHD3_JLYY_SUM { get; set; }
        public string ADHD4_BSTGZ { get; set; }
        public string ADHD4_ZYQX { get; set; }
        public string ADHD4_ZYQX_SUM { get; set; }
        public string ADHD4_DDCD { get; set; }
        public string ADHD4_DDCD_SUM { get; set; }
        public string ADHD4_GNSH { get; set; }
        public string ADHD4_GNSH_SUM { get; set; }
        public string ADHD4_JL { get; set; }
        public string CSZQM { get; set; }
        public string CSRQ { get; set; }
        public string OPERATE_NAME { get; set; }
        public string OPERATE_CODE { get; set; }
        public string OPERATE_TIME { get; set; }
        public string UPDATE_NAME { get; set; }
        public string UPDATE_CODE { get; set; }
        public string UPDATE_TIME { get; set; }
        public string SZYS { get; set; }
        public string HOSPITAL { get; set; }
    }
}
