//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CP_CDI_TAB
    {
        public int ID { get; set; }
        public decimal CHILD_ID { get; set; }
        public string YYLJ_DF { get; set; }
        public string YYLJ_YL { get; set; }
        public string YYLJ_P50 { get; set; }
        public string YYLJ_P75 { get; set; }
        public string CHBD_DF { get; set; }
        public string CHBD_YL { get; set; }
        public string CHBD_P50 { get; set; }
        public string CHBD_P75 { get; set; }
        public string BSTGZ { get; set; }
        public string ETDYR { get; set; }
        public string CSZQM { get; set; }
        public string CSRQ { get; set; }
        public string OPERATE_NAME { get; set; }
        public string OPERATE_CODE { get; set; }
        public string OPERATE_TIME { get; set; }
        public string UPDATE_NAME { get; set; }
        public string UPDATE_CODE { get; set; }
        public string UPDATE_TIME { get; set; }
        public string TYPE { get; set; }
        public string SZYS { get; set; }
        public string HOSPITAL { get; set; }
    }
}
