//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CP_DDST_TAB
    {
        public decimal ID { get; set; }
        public decimal CHILD_ID { get; set; }
        public string DDST_GRYSH { get; set; }
        public string DDST_JXYDNQ { get; set; }
        public string DDST_YYNQ { get; set; }
        public string DDST_DYDNQ { get; set; }
        public string DDST_JG { get; set; }
        public string CSZQM { get; set; }
        public string CSRQ { get; set; }
        public string OPERATE_NAME { get; set; }
        public string OPERATE_CODE { get; set; }
        public string OPERATE_TIME { get; set; }
        public string UPDATE_NAME { get; set; }
        public string UPDATE_CODE { get; set; }
        public string UPDATE_TIME { get; set; }
        public string SZYS { get; set; }
        public string HOSPITAL { get; set; }
        public string TYPE { get; set; }
        public Nullable<decimal> EXTERNALID { get; set; }
        public string JZ_DDST_GRYSH { get; set; }
        public string JZ_DDST_YYNQ { get; set; }
        public string JZ_DDST_DYDNQ { get; set; }
        public string JZ_DDST_JG { get; set; }
        public string JZ_DDST_JXYDNQ { get; set; }
    }
}
