//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CP_DREAM_TAB
    {
        public decimal ID { get; set; }
        public decimal CHILD_ID { get; set; }
        public string BZH_ZTYY { get; set; }
        public string BZH_TLLJ { get; set; }
        public string BZH_YYBD { get; set; }
        public string BZH_YY { get; set; }
        public string BZH_JF { get; set; }
        public string BFDJ_ZTYY { get; set; }
        public string BFDJ_TLLJ { get; set; }
        public string BFDJ_YYBD { get; set; }
        public string BFDJ_YY { get; set; }
        public string BFDJ_JF { get; set; }
        public string OPERATE_NAME { get; set; }
        public string OPERATE_CODE { get; set; }
        public string OPERATE_TIME { get; set; }
        public string UPDATE_NAME { get; set; }
        public string UPDATE_CODE { get; set; }
        public string UPDATE_TIME { get; set; }
        public string HOSPITAL { get; set; }
        public string SZYS { get; set; }
        public string CSZQM { get; set; }
        public string CSRQ { get; set; }
        public string DOCTOR_RESULT { get; set; }
        public string DOCTOR_ADVICE { get; set; }
        public string BZ { get; set; }
        public string BZ_VISIBLE { get; set; }
    }
}
