//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CP_GMYJC_TAB
    {
        public decimal ID { get; set; }
        public decimal CHILD_ID { get; set; }
        public string CSZQM { get; set; }
        public string CSRQ { get; set; }
        public string SZYS { get; set; }
        public string HOSPITAL { get; set; }
        public string OPERATE_NAME { get; set; }
        public string OPERATE_CODE { get; set; }
        public string OPERATE_TIME { get; set; }
        public string UPDATE_NAME { get; set; }
        public string UPDATE_CODE { get; set; }
        public string UPDATE_TIME { get; set; }
        public string JD_QIUZHEN { get; set; }
        public string JD_RESULT { get; set; }
        public string JR_QIUZHEN { get; set; }
        public string JR_RESULT { get; set; }
        public string NN_QIUZHEN { get; set; }
        public string NN_RESULT { get; set; }
        public string DD_QIUZHEN { get; set; }
        public string DD_RESULT { get; set; }
        public string HS_QIUZHEN { get; set; }
        public string HS_RESULT { get; set; }
        public string JY_QIUZHEN { get; set; }
        public string JY_RESULT { get; set; }
        public string X_QIUZHEN { get; set; }
        public string X_RESULT { get; set; }
        public string XM_QIUZHEN { get; set; }
        public string XM_RESULT { get; set; }
        public string JZ_QIUZHEN { get; set; }
        public string JZ_RESULT { get; set; }
        public string HT_QIUZHEN { get; set; }
        public string HT_RESULT { get; set; }
        public string DM_QIUZHEN { get; set; }
        public string DM_RESULT { get; set; }
        public string BC_QIUZHEN { get; set; }
        public string BC_RESULT { get; set; }
        public string YANG_QIUZHEN { get; set; }
        public string YIN_QIUZHEN { get; set; }
    }
}
