//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CP_GRIFFITHS_TAB
    {
        public decimal ID { get; set; }
        public decimal CHILD_ID { get; set; }
        public string PTRY { get; set; }
        public string PGMD { get; set; }
        public string BINGSHI { get; set; }
        public string A_ONE { get; set; }
        public string A_TWO { get; set; }
        public string A_THREE { get; set; }
        public string A_FOUR { get; set; }
        public string A_LZ { get; set; }
        public string A_BFW { get; set; }
        public string A_XDNL { get; set; }
        public string A_FYS { get; set; }
        public string A_MS { get; set; }
        public string B_ONE { get; set; }
        public string B_TWO { get; set; }
        public string B_THREE { get; set; }
        public string B_FOUR { get; set; }
        public string B_LZ { get; set; }
        public string B_BFW { get; set; }
        public string B_XDNL { get; set; }
        public string B_FYS { get; set; }
        public string B_MS { get; set; }
        public string C_ONE { get; set; }
        public string C_TWO { get; set; }
        public string C_THREE { get; set; }
        public string C_FOUR { get; set; }
        public string C_LZ { get; set; }
        public string C_BFW { get; set; }
        public string C_XDNL { get; set; }
        public string C_FYS { get; set; }
        public string C_MS { get; set; }
        public string D_ONE { get; set; }
        public string D_TWO { get; set; }
        public string D_THREE { get; set; }
        public string D_FOUR { get; set; }
        public string D_LZ { get; set; }
        public string D_BFW { get; set; }
        public string D_XDNL { get; set; }
        public string D_FYS { get; set; }
        public string D_MS { get; set; }
        public string E_ONE { get; set; }
        public string E_TWO { get; set; }
        public string E_THREE { get; set; }
        public string E_FOUR { get; set; }
        public string E_LZ { get; set; }
        public string E_BFW { get; set; }
        public string E_XDNL { get; set; }
        public string E_FYS { get; set; }
        public string E_MS { get; set; }
        public string F_ONE { get; set; }
        public string F_TWO { get; set; }
        public string F_THREE { get; set; }
        public string F_FOUR { get; set; }
        public string F_LZ { get; set; }
        public string F_BFW { get; set; }
        public string F_XDNL { get; set; }
        public string F_FYS { get; set; }
        public string F_MS { get; set; }
        public string CSZQM { get; set; }
        public string CSRQ { get; set; }
        public string OPERATE_NAME { get; set; }
        public string OPERATE_CODE { get; set; }
        public string OPERATE_TIME { get; set; }
        public string UPDATE_NAME { get; set; }
        public string UPDATE_CODE { get; set; }
        public string UPDATE_TIME { get; set; }
        public string HOSPITAL { get; set; }
        public string SZYS { get; set; }
        public string JZNL_N { get; set; }
        public string JZNL_Y { get; set; }
        public string JZNL_R { get; set; }
    }
}
