//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CP_GESELL_TAB
    {
        public decimal ID { get; set; }
        public decimal CHILD_ID { get; set; }
        public string SYX_DQ { get; set; }
        public string SYX_DA { get; set; }
        public string DYDN_DQ { get; set; }
        public string DYDN_DA { get; set; }
        public string XYDN_DQ { get; set; }
        public string XYDN_DA { get; set; }
        public string YYN_DQ { get; set; }
        public string YYN_DA { get; set; }
        public string GRSJ_DQ { get; set; }
        public string GRSJ_DA { get; set; }
        public string HZ { get; set; }
        public string FY { get; set; }
        public string ZYL { get; set; }
        public string QX { get; set; }
        public string CSZQM { get; set; }
        public string CSRQ { get; set; }
        public string OPERATE_NAME { get; set; }
        public string OPERATE_CODE { get; set; }
        public string OPERATE_TIME { get; set; }
        public string UPDATE_NAME { get; set; }
        public string UPDATE_CODE { get; set; }
        public string UPDATE_TIME { get; set; }
        public string SZYS { get; set; }
        public string HOSPITAL { get; set; }
        public string BZ { get; set; }
        public string BZ_VISIBLE { get; set; }
    }
}
