//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CP_PPVT_TAB
    {
        public decimal ID { get; set; }
        public decimal CHILD_ID { get; set; }
        public string PPVT_DD { get; set; }
        public string PPVT_CW { get; set; }
        public string PPVT_DF { get; set; }
        public string PPVT_ZS { get; set; }
        public string PPVT_ZL { get; set; }
        public string HRSY_ZF { get; set; }
        public string HRSY_ZS { get; set; }
        public string HRSY_ZL { get; set; }
        public string NLCY_DF { get; set; }
        public string NLCY_JG { get; set; }
        public string CYZ { get; set; }
        public string CYRQ { get; set; }
        public string OPERATE_NAME { get; set; }
        public string OPERATE_CODE { get; set; }
        public string OPERATE_TIME { get; set; }
        public string UPDATE_NAME { get; set; }
        public string UPDATE_CODE { get; set; }
        public string UPDATE_TIME { get; set; }
        public string SZYS { get; set; }
        public string HOSPITAL { get; set; }
        public string TYPE { get; set; }
        public Nullable<decimal> EXTERNALID { get; set; }
    }
}
