//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CP_PEABODY_TAB
    {
        public decimal ID { get; set; }
        public decimal CHILD_ID { get; set; }
        public string FANSHE_YSF { get; set; }
        public string FANSHE_XDNL { get; set; }
        public string FANSHE_BFW { get; set; }
        public string FANSHE_BZF1 { get; set; }
        public string FANSHE_BZF2 { get; set; }
        public string ZISHI_YSF { get; set; }
        public string ZISHI_XDNL { get; set; }
        public string ZISHI_BFW { get; set; }
        public string ZISHI_BZF1 { get; set; }
        public string ZISHI_BZF2 { get; set; }
        public string YIDONG_YSF { get; set; }
        public string YIDONG_XDNL { get; set; }
        public string YIDONG_BFW { get; set; }
        public string YIDONG_BZF1 { get; set; }
        public string YIDONG_BZF2 { get; set; }
        public string CAOZUO_YSF { get; set; }
        public string CAOZUO_XDNL { get; set; }
        public string CAOZUO_BFW { get; set; }
        public string CAOZUO_BZF1 { get; set; }
        public string CAOZUO_BZF2 { get; set; }
        public string ZHUAWO_YSF { get; set; }
        public string ZHUAWO_XDNL { get; set; }
        public string ZHUAWO_BFW { get; set; }
        public string ZHUAWO_BZF1 { get; set; }
        public string ZHUAWO_BZF2 { get; set; }
        public string SHIJUE_YSF { get; set; }
        public string SHIJUE_XDNL { get; set; }
        public string SHIJUE_BFW { get; set; }
        public string SHIJUE_BZF1 { get; set; }
        public string SHIJUE_BZF2 { get; set; }
        public string BZF_GMQ { get; set; }
        public string BZF_FMQ { get; set; }
        public string BZF_TMQ { get; set; }
        public string FYS_GMQ { get; set; }
        public string FYS_FMQ { get; set; }
        public string FYS_TMQ { get; set; }
        public string BFW_GMQ { get; set; }
        public string BFW_FMQ { get; set; }
        public string BFW_TMQ { get; set; }
        public string CSZQM { get; set; }
        public string CSRQ { get; set; }
        public string OPERATE_NAME { get; set; }
        public string OPERATE_CODE { get; set; }
        public string OPERATE_TIME { get; set; }
        public string UPDATE_NAME { get; set; }
        public string UPDATE_CODE { get; set; }
        public string UPDATE_TIME { get; set; }
        public string HOSPITAL { get; set; }
        public string SZYS { get; set; }
        public string JZNL_N { get; set; }
        public string JZNL_Y { get; set; }
        public string JZNL_R { get; set; }
    }
}
