//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CP_ZYLCY_TAB
    {
        public decimal ID { get; set; }
        public decimal CHILD_ID { get; set; }
        public string ZYLCY_SJ_FEN { get; set; }
        public string ZYLCY_SJ_MIAO { get; set; }
        public string ZYLCY_HC { get; set; }
        public string ZYLCY_LH { get; set; }
        public string ZYLCY_DF { get; set; }
        public string ZYLCY_PJ { get; set; }
        public string RWCY_SJ_FEN { get; set; }
        public string RWCY_SJ_MIAO { get; set; }
        public string RWCY_DDTS { get; set; }
        public string RWCY_IQ { get; set; }
        public string RWCY_BFWDJ { get; set; }
        public string SJYD_YSFS { get; set; }
        public string SJYD_IQ { get; set; }
        public string SJYD_VMI_SUI { get; set; }
        public string SJYD_VMI_YUE { get; set; }
        public string SJYD_SZJ_SUI { get; set; }
        public string SJYD_SZJ_YUE { get; set; }
        public string SJYD_DZ_SUI { get; set; }
        public string SJYD_DZ_YUE { get; set; }
        public string CYZ { get; set; }
        public string CYRQ { get; set; }
        public string OPERATE_NAME { get; set; }
        public string OPERATE_CODE { get; set; }
        public string OPERATE_TIME { get; set; }
        public string UPDATE_NAME { get; set; }
        public string UPDATE_CODE { get; set; }
        public string UPDATE_TIME { get; set; }
        public string SZYS { get; set; }
        public string HOSPITAL { get; set; }
        public string TYPE { get; set; }
    }
}
