//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}
    
        //public virtual DbSet<tb_healthcheck_moban> tb_healthcheck_moban { get; set; }
        //public virtual DbSet<sys_menus> sys_menus { get; set; }
        //public virtual DbSet<tb_childbase> tb_childbase { get; set; }
        //public virtual DbSet<sys_role> sys_role { get; set; }
        //public virtual DbSet<sys_role_menu> sys_role_menu { get; set; }
        //public virtual DbSet<sys_users> sys_users { get; set; }
        //public virtual DbSet<cp_yy_cou> cp_yy_cou { get; set; }
        //public virtual DbSet<temp_report> temp_report { get; set; }
        //public virtual DbSet<temp_report_node> temp_report_node { get; set; }
        //public virtual DbSet<xl_yy_cou> xl_yy_cou { get; set; }
        //public virtual DbSet<xl_yy_tab> xl_yy_tab { get; set; }
        //public virtual DbSet<hs_yy_gw_tab> hs_yy_gw_tab { get; set; }
        //public virtual DbSet<hs_yy_qt_tab> hs_yy_qt_tab { get; set; }
        //public virtual DbSet<hs_yy_xx_tab> hs_yy_xx_tab { get; set; }
        //public virtual DbSet<mb_zd> mb_zd { get; set; }
        //public virtual DbSet<mb_wy> mb_wy { get; set; }
        //public virtual DbSet<tb_childcheck> tb_childcheck { get; set; }
        //public virtual DbSet<cp_dream_tab> cp_dream_tab { get; set; }
        //public virtual DbSet<cp_gmyjc_tab> cp_gmyjc_tab { get; set; }
        //public virtual DbSet<cp_gyqt_tab> cp_gyqt_tab { get; set; }
        //public virtual DbSet<cp_gy_tab> cp_gy_tab { get; set; }
        //public virtual DbSet<cp_peabody_tab> cp_peabody_tab { get; set; }
        //public virtual DbSet<tab_bzfzh_Num> tab_bzfzh_Num { get; set; }
        //public virtual DbSet<tab_dept_data> tab_dept_data { get; set; }
        //public virtual DbSet<tab_Peabody_Num> tab_Peabody_Num { get; set; }
        //public virtual DbSet<tab_person_data> tab_person_data { get; set; }
        //public virtual DbSet<cp_ppvt_tab> cp_ppvt_tab { get; set; }
        //public virtual DbSet<cp_zqyyfyjc_tab> cp_zqyyfyjc_tab { get; set; }
        //public virtual DbSet<cp_zylcy_tab> cp_zylcy_tab { get; set; }
        //public virtual DbSet<cp_cdi1_tab> cp_cdi1_tab { get; set; }
        //public virtual DbSet<cp_cdi_tab> cp_cdi_tab { get; set; }
        //public virtual DbSet<cp_adhd_tab> cp_adhd_tab { get; set; }
        //public virtual DbSet<cp_ados1_tab> cp_ados1_tab { get; set; }
        //public virtual DbSet<cp_ados2_tab> cp_ados2_tab { get; set; }
        //public virtual DbSet<cp_ados3_tab> cp_ados3_tab { get; set; }
        //public virtual DbSet<cp_ados4_tab> cp_ados4_tab { get; set; }
        //public virtual DbSet<cp_asd1_tab> cp_asd1_tab { get; set; }
        //public virtual DbSet<cp_asd2_tab> cp_asd2_tab { get; set; }
        //public virtual DbSet<cp_gesell_tab> cp_gesell_tab { get; set; }
        //public virtual DbSet<cp_sm_tab> cp_sm_tab { get; set; }
        //public virtual DbSet<cp_wisc_tab> cp_wisc_tab { get; set; }
        //public virtual DbSet<cp_wycsi_tab> cp_wycsi_tab { get; set; }
        //public virtual DbSet<cp_yy_tab> cp_yy_tab { get; set; }
        //public virtual DbSet<cp_dst_tab> cp_dst_tab { get; set; }
        //public virtual DbSet<cp_tpch_tab> cp_tpch_tab { get; set; }
        //public virtual DbSet<yy_pz_tab> yy_pz_tab { get; set; }
        //public virtual DbSet<yy_asd_tab> yy_asd_tab { get; set; }
        //public virtual DbSet<yy_pz_details_tab> yy_pz_details_tab { get; set; }
        //public virtual DbSet<tab_templet_Info> tab_templet_Info { get; set; }
        //public virtual DbSet<tab_ysf_xdnl> tab_ysf_xdnl { get; set; }
        //public virtual DbSet<tab_yysc_Num> tab_yysc_Num { get; set; }
        //public virtual DbSet<cp_ptoni_tab> cp_ptoni_tab { get; set; }
        //public virtual DbSet<cp_ddst_tab> cp_ddst_tab { get; set; }
        //public virtual DbSet<ys_gdzpxza_tab> ys_gdzpxza_tab { get; set; }
        //public virtual DbSet<ys_ywgm_tab> ys_ywgm_tab { get; set; }
        //public virtual DbSet<ys_yybl_tab> ys_yybl_tab { get; set; }
    }
}
