//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MB_ZD
    {
        public decimal ID { get; set; }
        public decimal YFKS { get; set; }
        public decimal YFJS { get; set; }
        public string WYZD { get; set; }
        public string ZJZD { get; set; }
    }
}
