//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OracleEntities : DbContext
    {
        public OracleEntities()
            : base("name=OracleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEPT> DEPTs { get; set; }
        public virtual DbSet<EMP> EMPs { get; set; }
        public virtual DbSet<CHILD_GAOWEIGEAN> CHILD_GAOWEIGEAN { get; set; }
        public virtual DbSet<CHILD_GAOWEIGEAN_RECORD> CHILD_GAOWEIGEAN_RECORD { get; set; }
        public virtual DbSet<CHILD_GOULOUGEAN_RECORD> CHILD_GOULOUGEAN_RECORD { get; set; }
        public virtual DbSet<CHILD_JIBINGGUANLI> CHILD_JIBINGGUANLI { get; set; }
        public virtual DbSet<CHILD_JIBINGGUANLI_RECORD> CHILD_JIBINGGUANLI_RECORD { get; set; }
        public virtual DbSet<CHILD_PINXUEGEAN_RECORD> CHILD_PINXUEGEAN_RECORD { get; set; }
        public virtual DbSet<CHILD_STANDARD> CHILD_STANDARD { get; set; }
        public virtual DbSet<CHILD_STANDARD_BMI> CHILD_STANDARD_BMI { get; set; }
        public virtual DbSet<CHILD_STANDARD_W_H> CHILD_STANDARD_W_H { get; set; }
        public virtual DbSet<CHILD_XINLIXINGWEI> CHILD_XINLIXINGWEI { get; set; }
        public virtual DbSet<CHILD_XINLIXINGWEI_RECORD> CHILD_XINLIXINGWEI_RECORD { get; set; }
        public virtual DbSet<CHILD_YINGYANGGEAN> CHILD_YINGYANGGEAN { get; set; }
        public virtual DbSet<CHILD_YINGYANGGEAN_RECORD> CHILD_YINGYANGGEAN_RECORD { get; set; }
        public virtual DbSet<CP_ADHD_TAB> CP_ADHD_TAB { get; set; }
        public virtual DbSet<CP_ADOS1_TAB> CP_ADOS1_TAB { get; set; }
        public virtual DbSet<CP_ADOS2_TAB> CP_ADOS2_TAB { get; set; }
        public virtual DbSet<CP_ADOS3_TAB> CP_ADOS3_TAB { get; set; }
        public virtual DbSet<CP_ADOS4_TAB> CP_ADOS4_TAB { get; set; }
        public virtual DbSet<CP_ASD1_TAB> CP_ASD1_TAB { get; set; }
        public virtual DbSet<CP_ASD2_TAB> CP_ASD2_TAB { get; set; }
        public virtual DbSet<CP_CDI_TAB> CP_CDI_TAB { get; set; }
        public virtual DbSet<CP_CDI1_TAB> CP_CDI1_TAB { get; set; }
        public virtual DbSet<CP_DDST_TAB> CP_DDST_TAB { get; set; }
        public virtual DbSet<CP_DREAM_TAB> CP_DREAM_TAB { get; set; }
        public virtual DbSet<CP_DST_TAB> CP_DST_TAB { get; set; }
        public virtual DbSet<CP_GESELL_TAB> CP_GESELL_TAB { get; set; }
        public virtual DbSet<CP_GMYJC_TAB> CP_GMYJC_TAB { get; set; }
        public virtual DbSet<CP_GRIFFITHS_TAB> CP_GRIFFITHS_TAB { get; set; }
        public virtual DbSet<CP_GY_TAB> CP_GY_TAB { get; set; }
        public virtual DbSet<CP_GYQT_TAB> CP_GYQT_TAB { get; set; }
        public virtual DbSet<CP_PEABODY_TAB> CP_PEABODY_TAB { get; set; }
        public virtual DbSet<CP_PPVT_TAB> CP_PPVT_TAB { get; set; }
        public virtual DbSet<CP_PTONI_TAB> CP_PTONI_TAB { get; set; }
        public virtual DbSet<CP_SM_TAB> CP_SM_TAB { get; set; }
        public virtual DbSet<CP_TPCH_TAB> CP_TPCH_TAB { get; set; }
        public virtual DbSet<CP_WISC_TAB> CP_WISC_TAB { get; set; }
        public virtual DbSet<CP_WYCSI_TAB> CP_WYCSI_TAB { get; set; }
        public virtual DbSet<CP_YY_COU> CP_YY_COU { get; set; }
        public virtual DbSet<CP_YY_TAB> CP_YY_TAB { get; set; }
        public virtual DbSet<CP_ZQYYFYJC_TAB> CP_ZQYYFYJC_TAB { get; set; }
        public virtual DbSet<CP_ZYLCY_TAB> CP_ZYLCY_TAB { get; set; }
        public virtual DbSet<HS_YY_GW_TAB> HS_YY_GW_TAB { get; set; }
        public virtual DbSet<HS_YY_QT_TAB> HS_YY_QT_TAB { get; set; }
        public virtual DbSet<HS_YY_XX_TAB> HS_YY_XX_TAB { get; set; }
        public virtual DbSet<MB_WY> MB_WY { get; set; }
        public virtual DbSet<MB_ZD> MB_ZD { get; set; }
        public virtual DbSet<SYS_MENUS> SYS_MENUS { get; set; }
        public virtual DbSet<SYS_ROLE> SYS_ROLE { get; set; }
        public virtual DbSet<SYS_ROLE_MENU> SYS_ROLE_MENU { get; set; }
        public virtual DbSet<SYS_USERS> SYS_USERS { get; set; }
        public virtual DbSet<TAB_BZFZH_NUM> TAB_BZFZH_NUM { get; set; }
        public virtual DbSet<TAB_DEPT_DATA> TAB_DEPT_DATA { get; set; }
        public virtual DbSet<TAB_PEABODY_NUM> TAB_PEABODY_NUM { get; set; }
        public virtual DbSet<TAB_PERSON_DATA> TAB_PERSON_DATA { get; set; }
        public virtual DbSet<TAB_TEMPLET_INFO> TAB_TEMPLET_INFO { get; set; }
        public virtual DbSet<TAB_YSF_XDNL> TAB_YSF_XDNL { get; set; }
        public virtual DbSet<TAB_YYSC_NUM> TAB_YYSC_NUM { get; set; }
        public virtual DbSet<TB_BAOJIANGUID> TB_BAOJIANGUID { get; set; }
        public virtual DbSet<TB_CHILDBASE> TB_CHILDBASE { get; set; }
        public virtual DbSet<TB_CHILDCHECK> TB_CHILDCHECK { get; set; }
        public virtual DbSet<TB_CHILDCHECK_MOBAN> TB_CHILDCHECK_MOBAN { get; set; }
        public virtual DbSet<TB_GAOWEI> TB_GAOWEI { get; set; }
        public virtual DbSet<TB_GAOWEI_RECORD> TB_GAOWEI_RECORD { get; set; }
        public virtual DbSet<TB_GAOWEICONTENT> TB_GAOWEICONTENT { get; set; }
        public virtual DbSet<TB_GAOWEIPROJECT> TB_GAOWEIPROJECT { get; set; }
        public virtual DbSet<TB_HEALTHCHECK_MOBAN> TB_HEALTHCHECK_MOBAN { get; set; }
        public virtual DbSet<TB_MIANYIAGE> TB_MIANYIAGE { get; set; }
        public virtual DbSet<TB_MOBAN> TB_MOBAN { get; set; }
        public virtual DbSet<TB_NUTRITIONGUID> TB_NUTRITIONGUID { get; set; }
        public virtual DbSet<TB_RUTUOCHECK> TB_RUTUOCHECK { get; set; }
        public virtual DbSet<TB_SETCHECKAGE> TB_SETCHECKAGE { get; set; }
        public virtual DbSet<TB_SETYIMIAO> TB_SETYIMIAO { get; set; }
        public virtual DbSet<TB_YIMIAO> TB_YIMIAO { get; set; }
        public virtual DbSet<TEMP_REPORT> TEMP_REPORT { get; set; }
        public virtual DbSet<TEMP_REPORT_NODE> TEMP_REPORT_NODE { get; set; }
        public virtual DbSet<UPDATEVERSION> UPDATEVERSIONs { get; set; }
        public virtual DbSet<XL_YY_COU> XL_YY_COU { get; set; }
        public virtual DbSet<XL_YY_TAB> XL_YY_TAB { get; set; }
        public virtual DbSet<YS_GDZPXZA_TAB> YS_GDZPXZA_TAB { get; set; }
        public virtual DbSet<YS_YWGM_TAB> YS_YWGM_TAB { get; set; }
        public virtual DbSet<YS_YYBL_TAB> YS_YYBL_TAB { get; set; }
        public virtual DbSet<YY_ASD_TAB> YY_ASD_TAB { get; set; }
        public virtual DbSet<YY_PZ_DETAILS_TAB> YY_PZ_DETAILS_TAB { get; set; }
        public virtual DbSet<YY_PZ_TAB> YY_PZ_TAB { get; set; }
    }
}
