//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_USERS
    {
        public decimal ID { get; set; }
        public string USER_CODE { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public string PHONE { get; set; }
        public string USER_TYPE { get; set; }
        public string ADDRESS { get; set; }
        public decimal PRE_MAX { get; set; }
        public string DEPT_ID { get; set; }
        public string WARD_ID { get; set; }
        public string ZHICHENG { get; set; }
        public string ZHIWU { get; set; }
        public string ROLE_CODE { get; set; }
        public string DEPT_NAME { get; set; }
        public string WARD_NAME { get; set; }
        public string GONGHAO { get; set; }
    }
}
