//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_MENUS
    {
        public decimal ID { get; set; }
        public string MENU_NAME { get; set; }
        public string MENU_TYPE { get; set; }
        public string MENU_LEVER { get; set; }
        public string MENU_PARENT { get; set; }
        public string MENU_CODE { get; set; }
        public string MENU_URL { get; set; }
        public string IS_CUSTOM { get; set; }
        public string IS_ENABLE { get; set; }
        public string MENU_IMAGE { get; set; }
        public string IS_DEFAULT { get; set; }
        public string MENU_PARA { get; set; }
    }
}
