//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_YSF_XDNL
    {
        public decimal ID { get; set; }
        public string YSF_FS { get; set; }
        public string YSF_ZS { get; set; }
        public string YSF_YD { get; set; }
        public string YSF_SWCZ { get; set; }
        public string YSF_ZW { get; set; }
        public string YSF_SJYD { get; set; }
        public string XDNL { get; set; }
    }
}
