//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_YYSC_NUM
    {
        public decimal ID { get; set; }
        public decimal YUELING { get; set; }
        public string P10 { get; set; }
        public string P25 { get; set; }
        public string P50 { get; set; }
        public string P75 { get; set; }
        public string P90 { get; set; }
        public string TYPE { get; set; }
    }
}
