//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_DEPT_DATA
    {
        public decimal ID { get; set; }
        public string DEPT_NAME { get; set; }
        public string DEPT_CODE { get; set; }
        public string DOCTOR_NAME { get; set; }
        public string HOSPITAL { get; set; }
    }
}
