//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_BZFZH_NUM
    {
        public decimal ID { get; set; }
        public string BZF_ZYD { get; set; }
        public string BZF_CDYD { get; set; }
        public string BZF_JXYD { get; set; }
        public string TO_S { get; set; }
        public string TO_BFW { get; set; }
    }
}
