//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CHILDCHECK
    {

        public int ID { get; set; }
        public decimal CHILDID { get; set; }
        public string CHECKAGE { get; set; }
        public string CHECKFACTAGE { get; set; }
        public string CHECKDAY { get; set; }
        public string DOCTORNAME { get; set; }
        public string CHECKHEIGHT { get; set; }
        public string CHECKWEIGHT { get; set; }
        public string CHECKTOUWEI { get; set; }
        public string CHECKZUOGAO { get; set; }
        public string checkzuogao { get; set; }
        public string CHECKTUNWEI { get; set; }
        public string CHECKQIANLU { get; set; }
        public string CHECKIQ { get; set; }
        public string CHECKZIPING { get; set; }
        public string YUCEHEIGHT { get; set; }
        public string LEFTYAN { get; set; }
        public string RIGHTYAN { get; set; }
        public string LEFTYANSHILI { get; set; }
        public string RIGHTYANSHILI { get; set; }
        public string XIESHI { get; set; }
        public string LEFTER { get; set; }
        public string RIGHTER { get; set; }
        public string LEFTERLISTEN { get; set; }
        public string RIGHTLISTEN { get; set; }
        public string CHECKBI { get; set; }
        public string KOUQIANG { get; set; }
        public string YACINUMBER { get; set; }
        public string YUCINUMBER { get; set; }
        public string SKIN { get; set; }
        public string LINGBAJIE { get; set; }
        public string BIANTAOTI { get; set; }
        public string XINZANG { get; set; }
        public string FEIBU { get; set; }
        public string GANZANG { get; set; }
        public string PIZANG { get; set; }
        public string QIZHI { get; set; }
        public string SIZHI { get; set; }
        public string XIONGBU { get; set; }
        public string MINIAOQI { get; set; }
        public string WUGUAN { get; set; }
        public string JIZHU { get; set; }
        public string PINGPQIU { get; set; }
        public string CHECKCONTENT { get; set; }
        public string YUFANGJIEZHONG { get; set; }
        public string BLOODSESU { get; set; }
        public string SHIWUGOUCHENG { get; set; }
        public string VITD { get; set; }
        public string BIGSPORT { get; set; }
        public string SPIRTSPORT { get; set; }
        public string LAGUAGE { get; set; }
        public string SIGNSOCIAL { get; set; }
        public string OTHERBINGSHI { get; set; }
        public string HANDLE { get; set; }
        public string DIAGNOSE { get; set; }
        public string CHECKMONTH { get; set; }
        public string FUZENDAY { get; set; }
        public string FUBU { get; set; }
        public string FUWEI { get; set; }
        public string NUERZHIDAO { get; set; }
        public string CHECKDIAGNOSE { get; set; }
        public string ZHUSHI { get; set; }
        public string FUSHI { get; set; }
        public string SHEHUI { get; set; }
        public string DONGZUO { get; set; }
        public string TOULU { get; set; }
        public string GOULOUBING { get; set; }
        public string ZONGHEFAZHAN { get; set; }
        public string FUZHUJIANCHA { get; set; }
        public string OTHERJIANCHA { get; set; }
        public string ZHUSU { get; set; }
        public string BINGSHI { get; set; }
        public string TIJIAN { get; set; }
        public string ZHENDUAN { get; set; }
        public string CHULI { get; set; }
        public string USER_CODE { get; set; }
        public string CK_FZ { get; set; }
        public string FUZENCOMBOBOX { get; set; }
        public string HOSPITAL { get; set; }
    }
}
