//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CHILDBASE
    {
        public decimal ID { get; set; }
        public string HEALTHCARDNO { get; set; }
        public string CHILDNAME { get; set; }
        public string CHILDGENDER { get; set; }
        public string BLOODTYPE { get; set; }
        public string CHILDBIRTHDAY { get; set; }
        public string CHILDBUILDDAY { get; set; }
        public string CHILDBUILDHOSPITAL { get; set; }
        public string FATHERNAME { get; set; }
        public string FATHERAGE { get; set; }
        public string FATHERHEIGHT { get; set; }
        public string FATHEREDUCATION { get; set; }
        public string FATHERJOB { get; set; }
        public string MOTHERNAME { get; set; }
        public string MOTHERAGE { get; set; }
        public string MOTHERHEIGHT { get; set; }
        public string MOTHEREDUCATION { get; set; }
        public string MOTHERJOB { get; set; }
        public string TELEPHONE { get; set; }
        public string ADDRESS { get; set; }
        public string NURSERYINSTITUTION { get; set; }
        public string IMMUNEUNIT { get; set; }
        public string IMMUNEDAY { get; set; }
        public string COMMUNITY { get; set; }
        public string CENSUSREGISTER { get; set; }
        public string CS_FETUS { get; set; }
        public string CS_PRODUCE { get; set; }
        public string CS_WEEK { get; set; }
        public string CS_DAY { get; set; }
        public string MODEDELIVERY { get; set; }
        public string PERINEUMINCISION { get; set; }
        public string FETUSNUMBER { get; set; }
        public string NEONATALCONDITION { get; set; }
        public string BIRTHWEIGHT { get; set; }
        public string BIRTHHEIGHT { get; set; }
        public string BIRTHADDRESS { get; set; }
        public string HOSPITALIZEDSTATES { get; set; }
        public string ONEMONTH { get; set; }
        public string INFOURMONTH { get; set; }
        public string FOURTOSIXMONTH { get; set; }
        public string YUNQI { get; set; }
        public string CHANQIANHEBING { get; set; }
        public string TOWNCOUNTRY { get; set; }
        public string IDENTITYNO { get; set; }
        public string STATUS { get; set; }
        public string GAOWEIYINSU { get; set; }
        public string YINGYANGBULIANG { get; set; }
        public string JIUZHENCARDNO { get; set; }
        public string LINSHI { get; set; }
        public string TELEPHONE2 { get; set; }
        public string ISPRE { get; set; }
        public string PROVINCE { get; set; }
        public string CITY { get; set; }
        public string AREA { get; set; }
        public string GERENSHI { get; set; }
        public string JIWANGSHI { get; set; }
        public string JIAZUSHI { get; set; }
        public string JTZZ_CX { get; set; }
        public string SFST { get; set; }
        public string SFZY { get; set; }
        public string SFZLB { get; set; }
        public string PATIENT_ID { get; set; }
        public string FUZENCOMBOBOX { get; set; }
        public string HOSPITAL { get; set; }
    }
}
