//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_GAOWEI_RECORD
    {
        public decimal ID { get; set; }
        public Nullable<decimal> CHILDID { get; set; }
        public string GAOWEIYINSU { get; set; }
        public string RECORDTIME { get; set; }
        public string STATUS { get; set; }
        public string DOCTORNAME { get; set; }
    }
}
