//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HEALTHCHECK_MOBAN
    {
        public long ID { get; set; }
        public string MOBAN_NAME { get; set; }
        public string MOBAN_TYPE { get; set; }
        public string ZHUSU { get; set; }
        public string BINGSHI { get; set; }
        public string TIJIAN { get; set; }
        public string ZHENDUAN { get; set; }
        public string CHULI { get; set; }
        public string CREATER_NAME { get; set; }
    }
}
