//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MOBAN
    {
        public decimal ID { get; set; }
        public string M_NAME { get; set; }
        public string M_TYPE { get; set; }
        public string M_CONTENT { get; set; }
        public string YF { get; set; }
        public string YFEND { get; set; }
    }
}
