//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_RUTUOCHECK
    {
        public long ID { get; set; }
        public Nullable<long> CD_ID { get; set; }
        public string CHILDNAME { get; set; }
        public string CHILDGENDER { get; set; }
        public string BIRTHDAY { get; set; }
        public byte[] CHILDPHOTO { get; set; }
        public string TUOYOUJIGOU { get; set; }
        public string JIWANGSHI { get; set; }
        public string JIBINGSHI { get; set; }
        public string GUOMINSHI { get; set; }
        public string CHUANRANBING { get; set; }
        public string FABINGDAY { get; set; }
        public string WEIGHT { get; set; }
        public string WEIGHTPJ { get; set; }
        public string HEIGHT { get; set; }
        public string HEIGHTPJ { get; set; }
        public string PIFUMAOFA { get; set; }
        public string LEFTYAN { get; set; }
        public string RIGHTYAN { get; set; }
        public string BIANTAOTI { get; set; }
        public string LEFTER { get; set; }
        public string RIGHTER { get; set; }
        public string XIN { get; set; }
        public string YACINUMBER { get; set; }
        public string YUNCINUMBER { get; set; }
        public string FEI { get; set; }
        public string GAN { get; set; }
        public string PI { get; set; }
        public string SHENGZHIQI { get; set; }
        public string OTHER { get; set; }
        public string GOULOUBING { get; set; }
        public string QIANLU { get; set; }
        public string CONTENT { get; set; }
        public string XUEHONG { get; set; }
        public string GANGNENG { get; set; }
        public string XGUANG { get; set; }
        public string XOTHER { get; set; }
        public string DOCTORYIJIAN { get; set; }
        public string DOCTORNAME { get; set; }
        public string CHECKDAY { get; set; }
        public string LEFTSHILI { get; set; }
        public string RIGHTSHILI { get; set; }
        public string ANBINGSUAN { get; set; }
        public string YANBU { get; set; }
        public string XIONGGUO { get; set; }
        public string TOULU { get; set; }
        public string SIZHI { get; set; }
        public string CHECKRESULT { get; set; }
    }
}
