//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SETYIMIAO
    {
        public long ID { get; set; }
        public string YIMIAONAME { get; set; }
        public string PRODUCTIONDAY { get; set; }
        public string FACTORNAME { get; set; }
        public string PIHAO { get; set; }
        public string GUIGE { get; set; }
        public string JILIANGUNIT { get; set; }
        public string MONTH { get; set; }
    }
}
