//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_YIMIAO
    {
        public decimal ID { get; set; }
        public string YIMIAO_NAME { get; set; }
        public string JZ_RQ { get; set; }
        public string XCJZ_RQ { get; set; }
        public Nullable<decimal> CD_ID { get; set; }
        public Nullable<decimal> YIMIAO_YF { get; set; }
    }
}
