//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_REPORT_NODE
    {
        public decimal ID { get; set; }
        public Nullable<decimal> REPORT_ID { get; set; }
        public string NODE_NAME { get; set; }
        public string NODE_TEXT { get; set; }
        public string ISTEAM { get; set; }
        public string NODE_AREA { get; set; }
        public string NODE_TYPE { get; set; }
        public string NODE_PREFIX { get; set; }
        public string NODE_SUFFIX { get; set; }
        public string NODE_FONTSIZE { get; set; }
        public string NODE_FONTNAME { get; set; }
        public string NODE_VALUE { get; set; }
        public string NODE_OFFSET { get; set; }
        public string NODE_WIDTH { get; set; }
        public string NODE_HEIGHT { get; set; }
        public string NODE_NUMBER { get; set; }
    }
}
