//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_REPORT
    {
        public decimal ID { get; set; }
        public string REPORT_NAME { get; set; }
        public string REPORT_DISPLAYNAME { get; set; }
        public string REPORT_DESC { get; set; }
        public string CREATER { get; set; }
        public string CREATE_TIME { get; set; }
        public string UPDATER { get; set; }
        public string UPDATE_TIME { get; set; }
        public string REPORT_PROCEDURE { get; set; }
        public string REPORT_XLS { get; set; }
    }
}
