//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class YS_GDZPXZA_TAB
    {
        public decimal ID { get; set; }
        public Nullable<decimal> CHILD_ID { get; set; }
        public string ZS_TEXT { get; set; }
        public string ZS_CHECK { get; set; }
        public string XBS_TEXT { get; set; }
        public string XBS_YYLJ { get; set; }
        public string XBS_YYBD { get; set; }
        public string XBS_FYYBD { get; set; }
        public string XBS_SHJW { get; set; }
        public string XBS_CFKB { get; set; }
        public string XBS_CF { get; set; }
        public string XBS_OTHER { get; set; }
        public string TESTNAME { get; set; }
        public string TESTDATE { get; set; }
    }
}
