//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class YS_YYBL_TAB
    {
        public decimal ID { get; set; }
        public Nullable<decimal> CHILD_ID { get; set; }
        public string ZS_CHECK { get; set; }
        public string XBS { get; set; }
        public string SC_G { get; set; }
        public string SC_P { get; set; }
        public string SC_YZ { get; set; }
        public string SC_FS { get; set; }
        public string SC_YY { get; set; }
        public string SC_WEIGHT { get; set; }
        public string SC_MQYQYY { get; set; }
        public string SC_ISMQJB { get; set; }
        public string SC_MQJB { get; set; }
        public string SC_ISBTS { get; set; }
        public string SC_BTS { get; set; }
        public string WY_SH { get; set; }
        public string WY_XS { get; set; }
        public string WY_QS { get; set; }
        public string WY_CNSD { get; set; }
        public string WY_JJCN { get; set; }
        public string WY_JSL { get; set; }
        public string WY_FSNL { get; set; }
        public string SZFY_DYD { get; set; }
        public string SZFY_JXYD { get; set; }
        public string SZFY_YY { get; set; }
        public string SZFY_GRSH { get; set; }
        public string YFJZ_JZ { get; set; }
        public string JWS_SB { get; set; }
        public string JWS_FXS { get; set; }
        public string JWS_FYS { get; set; }
        public string JWS_XCS { get; set; }
        public string JWS_SWGM { get; set; }
        public string JWS_YWGM { get; set; }
        public string JTHJ_FMTX { get; set; }
        public string JTHJ_YCS { get; set; }
        public string JTHJ_CRBS { get; set; }
        public string TJ_W { get; set; }
        public string TJ_L { get; set; }
        public string TJ_JS { get; set; }
        public string TESTNAME { get; set; }
        public string TESTDATE { get; set; }
    }
}
