//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class YS_YWGM_TAB
    {
        public decimal ID { get; set; }
        public Nullable<decimal> CHILD_ID { get; set; }
        public string ZS_ZZ { get; set; }
        public string ZS_TIME { get; set; }
        public string XBS_PF { get; set; }
        public string XBS_XHD { get; set; }
        public string XBS_HXD { get; set; }
        public string XBS_OTHER { get; set; }
        public string XBS_YSSWGX { get; set; }
        public string XBS_WYFS { get; set; }
        public string XBS_KYSW { get; set; }
        public string XBS_JSHZZSJ { get; set; }
        public string XBS_KZSW { get; set; }
        public string XBS_LSZZ { get; set; }
        public string XBS_JWQK { get; set; }
        public string XBS_GW_GWJZS { get; set; }
        public string XBS_GW_FMFS { get; set; }
        public string XBS_GW_YZ { get; set; }
        public string XBS_GW_JSSY { get; set; }
        public string XBS_CW { get; set; }
        public string TESTNAME { get; set; }
        public string TESTDATE { get; set; }
        public string XBS_FU { get; set; }
        public string XBS_MU { get; set; }
        public string XBS_TB { get; set; }
    }
}
