//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class YY_PZ_DETAILS_TAB
    {
        public decimal ID { get; set; }
        public decimal COUNTPERTIME { get; set; }
        public Nullable<decimal> PZID { get; set; }
        public string TIME { get; set; }
    }
}
