//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ys_gdzpxza_tab
    {
        public int id { get; set; }
        public Nullable<int> child_id { get; set; }
        public string zs_text { get; set; }
        public string zs_check { get; set; }
        public string xbs_text { get; set; }
        public string xbs_yylj { get; set; }
        public string xbs_yybd { get; set; }
        public string xbs_fyybd { get; set; }
        public string xbs_shjw { get; set; }
        public string xbs_cfkb { get; set; }
        public string xbs_cf { get; set; }
        public string xbs_other { get; set; }
        public string testName { get; set; }
        public string testDate { get; set; }
    }
}
