//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ys_ywgm_tab
    {
        public int id { get; set; }
        public Nullable<int> child_id { get; set; }
        public string zs_zz { get; set; }
        public string zs_time { get; set; }
        public string xbs_pf { get; set; }
        public string xbs_xhd { get; set; }
        public string xbs_hxd { get; set; }
        public string xbs_other { get; set; }
        public string xbs_ysswgx { get; set; }
        public string xbs_wyfs { get; set; }
        public string xbs_kysw { get; set; }
        public string xbs_jshzzsj { get; set; }
        public string xbs_kzsw { get; set; }
        public string xbs_lszz { get; set; }
        public string xbs_jwqk { get; set; }
        public string xbs_gw_gwjzs { get; set; }
        public string xbs_gw_fmfs { get; set; }
        public string xbs_gw_yz { get; set; }
        public string xbs_gw_jssy { get; set; }
        public string xbs_cw { get; set; }
        public string testName { get; set; }
        public string testDate { get; set; }
        public string xbs_fu { get; set; }
        public string xbs_mu { get; set; }
        public string xbs_tb { get; set; }
    }
}
