//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ys_yybl_tab
    {
        public int id { get; set; }
        public Nullable<int> child_id { get; set; }
        public string zs_check { get; set; }
        public string xbs { get; set; }
        public string sc_g { get; set; }
        public string sc_p { get; set; }
        public string sc_yz { get; set; }
        public string sc_fs { get; set; }
        public string sc_yy { get; set; }
        public string sc_weight { get; set; }
        public string sc_mqyqyy { get; set; }
        public string sc_ismqjb { get; set; }
        public string sc_mqjb { get; set; }
        public string sc_isbts { get; set; }
        public string sc_bts { get; set; }
        public string wy_sh { get; set; }
        public string wy_xs { get; set; }
        public string wy_qs { get; set; }
        public string wy_cnsd { get; set; }
        public string wy_jjcn { get; set; }
        public string wy_jsl { get; set; }
        public string wy_fsnl { get; set; }
        public string szfy_dyd { get; set; }
        public string szfy_jxyd { get; set; }
        public string szfy_yy { get; set; }
        public string szfy_grsh { get; set; }
        public string yfjz_jz { get; set; }
        public string jws_sb { get; set; }
        public string jws_fxs { get; set; }
        public string jws_fys { get; set; }
        public string jws_xcs { get; set; }
        public string jws_swgm { get; set; }
        public string jws_ywgm { get; set; }
        public string jthj_fmtx { get; set; }
        public string jthj_ycs { get; set; }
        public string jthj_crbs { get; set; }
        public string tj_w { get; set; }
        public string tj_l { get; set; }
        public string tj_js { get; set; }
        public string testName { get; set; }
        public string testDate { get; set; }
    }
}
